version: '3.8'

networks:
  aw-networks:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheus_data:/prometheus
    networks:
      - aw-networks
    ports:
      - 9090:9090
      
  grafana:
    image: grafana/grafana:latest
    networks:
      - aw-networks
    ports:
      - 3000:3000
      
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD= root
      - MYSQL_DATABASE=database
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/var/lib/mysql

  app:
    image: api-contas-bancarias
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prod