version: 1

services:
  - type: web
    name: prometheus
    plan: free
    env: production
    start_command: ["prometheus", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"]
    http_port: 9090
    ports:
      - name: http
        port: 9090

  - type: web
    name: app
    plan: free
    env: production
    start_command: ["java", "-jar", "app.jar"]
    http_port: 8080
    ports:
      - name: http
        port: 8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  - name: prometheus_data
