name: continuos integration - verify version project

on:
  push:
    branches:
      - test-ci
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_versions:
    name: Project Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - test-ci
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Verificar versão na branch ${{ matrix.branch }}
        id: actions_project_version_check
        uses: avides/actions-project-version-check@v1.4.0
        with:
          token: ${{ secrets.GIT_TOKEN }}
          file-to-check: pom.xml

      - name: Armazenar versões em variáveis
        run: |
          if [ "${{ matrix.branch }}" == "main" ]; then
            echo '| Branch Scan   | Project Version |' >> $GITHUB_STEP_SUMMARY
            echo '| :------------ | :-------------: |' >> $GITHUB_STEP_SUMMARY
            echo '| ${{ matrix.branch }} | ${{ steps.actions_project_version_check.outputs.version }} |' >> $GITHUB_STEP_SUMMARY
          else
            echo '| Branch Scan   | Project Version |' >> $GITHUB_STEP_SUMMARY
            echo '| :------------ | :-------------: |' >> $GITHUB_STEP_SUMMARY
            echo '| ${{ github.ref_name }} | ${{ steps.actions_project_version_check.outputs.version }} |' >> $GITHUB_STEP_SUMMARY
          fi