name: docker continuos delivery

on:
  push:
    branches:
      - feature/deploy-docker
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Directory /app
        run: ls -a

      - name: Run and Build Containers
        run: |
          docker-compose up -d --build

          # Wait for services to initialize (customize as needed)
          sleep 180
      
      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image

      - name: Show a List of Running Containers
        run: docker ps

      - name: Show a List of All Containers
        run: docker ps -a
      
      - name: Show a List of All Images
        run: docker images

  deploy:
    name: Deploy Dockerhub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Caminho
        run: pwd

      - name: Docker Directory /app
        run: ls -a

      - name: Show a List of All Images
        run: docker images

      - name: Faça o login no Docker Hub (ou outro registro)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          docker load -i docker-image.tar
        
      - name: Show a List of All Images
        run: docker images

      - name: Faça o push da imagem para o Docker Hub
        run: docker tag api-contas-bancarias macgii/api-contas-bancarias

      - name: Show a List of All Images
        run: docker images

      - name: Faça o push da imagem para o Docker Hub
        run: docker push macgii/api-contas-bancarias:latest
