name: docker continuos delivery

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dcoker Listing Files and Directories with Detailed Information
        run: ls -a

      - name: Run and Build Containers
        run: |
          docker-compose up -d --build

          # Wait for services to initialize (customize as needed)
          sleep 180

      - name: Show a List of Running Containers
        run: docker ps

      - name: Show a List of All Containers
        run: docker ps -a
      
      - name: Show a List of All Images
        run: docker images

  deploy:
    name: Deploy Dockerhub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Image
        run: docker-compose build

      - name: Show a List of All Images
        run: docker images

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io
        
      - name: Creating a Docker Image Tag for Pushing to Docker Hub
        run: docker tag api-contas-bancarias macgii/api-contas-bancarias

      - name: Show a List of All Images
        run: docker images

      - name: Push the image to Docker Hub
        run: docker push macgii/api-contas-bancarias:latest
