name: Verify Version

on:
  push:
    branches:
      - feature/deploy-docker

jobs:
  verify_version:
    name: Semantic Version Verify
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: Bump version
        uses: jakejarvis/semver@v0.11.0
        with:
          version: 'auto'
          bump: 'patch'
          token: ${{ secrets.GIT_TOKEN }}

