name: Docker Continuos Delivery

on:
  push:
    branches:
      - feature/deploy-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Faça o build e teste
      run: |
          docker-compose up -d --build

          # Wait for services to initialize (customize as needed)
          sleep 180

    - name: Show a List of All Images
      run: docker images

    - name: Faça o login no Docker Hub (ou outro registro)
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Faça o push da imagem para o Docker Hub
      run: docker push macgii/api-contas-bancarias:latest

